### ISSUE TITLE
Support Linux RAID devices

### ISSUE THREAD

**Issue by jas4711** [open-power/petitboot#31]
Hello.  Thanks for petitboot!  I am using on my ASUS D16 mainboard. I have not been able to make petitboot find anything on my RAID devices.  I installed through Debian 8.9 and have tried both RAID1 with a LVM on containing the / system.  I have also tried a RAID1 partition with a ext4 /boot partition on. When installing it again and creating a /boot that is primary ext4 partition, it does find the partition and can boot from it.  However, having RAID booting working would be nice.  Is this a feature enhancement request, or is it a bug that it does not work for?

**Comment by sammj** [comment]
Hi @jas4711. This should work - LVM support was added only very recently but RAID support has been around for a while. This may depend a bit on how you are building Petitboot however. You can see [here](https://github.com/open-power/op-build/tree/master/openpower/package/petitboot) that when building with Buildroot we add in some extra udev rules to make sure RAID devices are recognised correctly.
To help track this down can you please post
- the Petitboot version
- kernel log and `/var/log/petitboot/pb-discover.log` (you can use `pb-sos` to collect these easily)
- how you're building the Petitboot environment, eg Buildroot, etc?

Thanks!

**Comment by sammj** [comment]
Assuming everything was ok here, reopen if still an issue.

**Comment by brandonhawbaker** [comment]
@sammj I'm currently having an issue getting PetitBoot to recognize my RAID 1 array created with mdadm using a Kubuntu live usb drive using two nvme drives.  I'm using an ASUS KGPE-D16 (vikings store) also with CoreBoot+PetitBoot.  I can assembly them from the live distro and see the file system.  I can also see the drives when I drop to a shell from PetitBoot as:

nvme0
nvme0n1
nvme0n1p1

nvme1
nvme1n1
nvme1n1p1

I can use fdisk -l to see that both nvme0n1p1 and nvme1n1p1 both have an asterisk for the boot column, start = 65, end = 30524162, blocks = 488385560, id = fd, system = "Linux raid autodetect".  However, not only does no boot menu item for these drives show up after essentially following these instructions:

https://askubuntu.com/questions/505446/how-to-install-ubuntu-14-04-with-raid-1-using-desktop-installer

 But I don't see my raid 1 array md0, md0p1, or md0p2, so I'm not sure how it would detect it without some kind of default modules for raid detection.  Of course, I can't change the settings for PetitBoot because it's built into the ROM.  I have even tried to mount /dev/nvme0n1p1/2 to a temporary folder I create at /var/n0, but it fails with "No such device".  I have yet to confirm, but it's almost like it requires two non-RAID boot partitions it can recognize rather than being able to recognize typical software RAID by default.  Is this by design?

**Comment by jk-ozlabs** [comment]
The petitboot image does not have any state about your raid config; so it will need to be able to access your devices in their "raw" state, without having that config. That usually means that your devices should be mountable individually.

If this isn't possible without composing the RAID device under petitboot, I'd suggest using a boot partition for petitboot to read the config + payload from.

From your "No such device" error there: can you check out the kernel `dmesg` and `/var/log/pb-discover.log`  from the petitboot environment to see what's going wrong? What's the actual mount command you're using?

**Comment by brandonhawbaker** [comment]
I bailed on trying to get petitboot to recognize the mdadm raid device wholesale, so I instead created a separate boot partition that is non-raid.  The command I had used to test to see if I could mount the drive was:

mount /dev/nvme0np1 /var/n0

I tried very hard to get PetitBoot to recognize my boot partitions with little success.  I eventually ended up using the Kubuntu installation wizard to install /boot to the separate boot partition, which allowed petitboot to finally see the boot partition.  I still need to get grub/initramfs to have enough mdadm awareness to load /dev/md0, but I don't think that part is related to petitboot.  I do wish it was clearer to understand exactly what petitboot expects to find to detect it as a bootable device?  I tried creating an /EFI/BOOT folder.  I tried marking the partition as bootable.  I had run install-grub to /dev/sda an /dev/sdb, etc.  It seems like no matter what I tried, petitboot could see the drive and partitions and even mount them, but it would not bring up a menu option, until I had the Kubuntu installation set it up.
