### ISSUE TITLE
Autoboot Timeout expires before netboot option is established

### ISSUE THREAD

**Issue by robers97** [open-power/petitboot#43]
On large cluster installs, it is possible that the DHCP exchange for network boot images does not complete ahead of the Autoboot timeout.  Admins are finding nodes that do not autoboot idling at the petitboot menu only needing to hit return to complete the boot process.

When a new network device is found, can we retrigger the autoboot timeout counter to make autoboot more robust in contentious network situations?

**Comment by sammj** [comment]
The autoboot timeout only begins once Petitboot finds a valid autoboot option; so if the countdown started and did not encounter an error the machine would have booted rather than stopping at the menu (eg, it would have booted to disk, etc).
If Petitboot isn't booting to the network then something must have interrupted the boot process. Assuming this is the same issue discussed elsewhere then we'll need to run `pb-sos` when a machine is found like this, the logs should say why Petitboot hasn't booted.

**Comment by robers97** [comment]
I will get the logs, but in general once I see the decision to boot, I have never seen an interruption.

**Comment by sammj** [comment]
Catching up this issue, the machines in question were found to be failing to boot because wget was timing out trying to download the initrd. This is most likely due to particularly intense network congestion and the size of the boot images; however from Petitboot's perspective updating to include the requery feature in https://github.com/open-power/petitboot/commit/6fa0edfb029726968cbacad9d4e193a345956ff3 was enough to overcome that.
