### ISSUE TITLE
Where can I find the configuration documentation?

### ISSUE THREAD

**Issue by larryqiann** [open-power/petitboot#79]
There seems to be some mention of some configuration files that Petitboot will look for at boot. Is there any documentation about the options and format of these files, and how to configure advanced features like network booting, etc?

Thanks!

**Comment by klauskiwi** [comment]
Unfortunately we don't have a lot of documentation on Petitboot.. Contributions are always welcome.

The basic concept for petitboot configuration is that it tries to parse grub(2), pxe, syslinux etc configuration so you'd need to refer to each of those documentations for the proper syntax. You can check some of the configurations examples being used in by the automated testing here: https://github.com/open-power/petitboot/tree/master/test/parser/data

For the native format, again no formal documentation but the format is extremely simple:
```
# OpenPower Petitboot "Native format" example
# Use it with the "Retrieve config from URL" in Petitboot
# rough syntax:
#
# label this is your label
# kernel http/https/ftp://url-to-vmlinuz
# initrd http/https/ftp://url-to-initrd
# append command-line-options
#

label Linux Fedora 33 ppc64le
   kernel https://download-ib01.fedoraproject.org/pub/fedora-secondary/releases/33/Everything/ppc64le/os/ppc/ppc64/vmlinuz
   initrd https://download-ib01.fedoraproject.org/pub/fedora-secondary/releases/33/Everything/ppc64le/os/ppc/ppc64/initrd.img
   append inst.repo=https://download-ib01.fedoraproject.org/pub/fedora-secondary/releases/33/Everything/ppc64le/os/ inst.vnc inst.sshd
````
Note you might need to pass additional command-line options (`append` line) so that the Distro installer can find your network, disks etc..

Here are some more links that you might be interested on:
* https://www.youtube.com/watch?v=4JbDb4bRBK4
* https://sthbrx.github.io/category/petitboot.html
* https://www.ibm.com/support/knowledgecenter/linuxonibm/liabw/liabppetitboot.html
* https://github.com/open-power/petitboot/blob/master/doc/func/parsers.rst
